#!/bin/sh

genconf() {
local fn=$1
local idx=$(echo $fn | tr -C -d '0-9')
if [ -z "$idx" ]; then
	echo "conf name has to be serverDIGIT.conf"
	exit 1
fi
local port=$(expr 110 + $idx)
local tun=$(expr $idx - 1)
cat << EOF > $fn
dev tun$tun
secret /etc/openvpn/static.key
port $port
proto udp
ifconfig 10.8.$tun.1 10.8.$tun.2
comp-lzo
script-security 2
up /etc/openvpn/up-openvpn
#tun-mtu 8080
#fragment 0
#mssfix 0
#daemon
keepalive 30 90
EOF
}

if [ $# -lt 1 ]; then
	echo "Missing output conf name"
	exit 1
fi

while [ $# -gt 0 ]; do
	genconf $1
	shift
done
