#!/bin/sh

genconf() {
local ofn=$1
[ -f $ofn ] && { echo "file $ofn already existed, removing it first"; exit 1; }
local num=$(echo $ofn | tr -C -d '0-9')
[ -z "$num" ] && { echo "configuration file name has to be like server123.conf" ; exit 1; }
local port=$((110+$num))
local tun=$(($num-1))
cat << EOF > $ofn
dev tun$tun
secret /etc/openvpn/static.key
port $port
proto udp
ifconfig 10.8.$tun.1 10.8.$tun.2
comp-lzo
script-security 2
up /etc/openvpn/up-openvpn
keepalive 30 90
EOF
}

if [ $# -lt 1 ]; then
	echo "missing openvpn configuration file name for outputing."
	echo "Usage: $0 <server1.conf>"
	exit 1
fi

while [ $# -gt 0 ]; do
	genconf $1
	shift
done
